version: "2"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:9700"
    environment:
      - "MODE=offline"
      - "NETWORK=mainnet-22816573"
    volumes:
      - "./data:/root/data/"
    labels:
      service_group: rosetta